// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2G0fyNdS5lMaVB1RtdBd7ffDoof45MKU',
    appId: '1:737088097620:web:9103a8f6ea4eb63adfccc1',
    messagingSenderId: '737088097620',
    projectId: 'fir-test-243ec',
    authDomain: 'fir-test-243ec.firebaseapp.com',
    storageBucket: 'fir-test-243ec.appspot.com',
    measurementId: 'G-99NE9GJ7DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0iFKUDS0XX7VJAB_LZpbVdQwOBD-sS6M',
    appId: '1:737088097620:android:42edd1ef09a1a237dfccc1',
    messagingSenderId: '737088097620',
    projectId: 'fir-test-243ec',
    storageBucket: 'fir-test-243ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVgMYNWjmtF4JBzVHnadSV7O278asYkgA',
    appId: '1:737088097620:ios:876f2d91c121213adfccc1',
    messagingSenderId: '737088097620',
    projectId: 'fir-test-243ec',
    storageBucket: 'fir-test-243ec.appspot.com',
    iosClientId: '737088097620-a2mh01n53g83ss5n9fqdvaut6gl44cis.apps.googleusercontent.com',
    iosBundleId: 'com.example.test2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVgMYNWjmtF4JBzVHnadSV7O278asYkgA',
    appId: '1:737088097620:ios:876f2d91c121213adfccc1',
    messagingSenderId: '737088097620',
    projectId: 'fir-test-243ec',
    storageBucket: 'fir-test-243ec.appspot.com',
    iosClientId: '737088097620-a2mh01n53g83ss5n9fqdvaut6gl44cis.apps.googleusercontent.com',
    iosBundleId: 'com.example.test2',
  );
}
